### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by ewnd9** [ewnd9/generator-ewnd9-npm#1]
- [x] script to instantiate each type of project https://github.com/ewnd9/generator-ewnd9-npm/commit/cb5c1517477a13898f2dcaad20b76147d6a991db
- [x] include those boilerplates to git for observation https://github.com/ewnd9/generator-ewnd9-npm/commit/0f4351dfb95f29e9d8f210d6623391cdadf997b2
## projects
- [x] extract [`tracklister-app`](https://github.com/ewnd9/tracklister-app) to an react-webpack project https://github.com/ewnd9/generator-ewnd9-npm/commit/afd6000ba67212d3afe94b719c501b82d801c5d4
- [x] extract [`record-desktop`](https://github.com/ewnd9/record-desktop) to an electron project https://github.com/ewnd9/generator-ewnd9-npm/commit/7b6502e2b249824b2dc73e4bd5eb71e582b8aafb
